### ISSUE TITLE
Bug: invocation succeeds even though the Wasm wrap invokes a plugin that is not present

### ISSUE THREAD

**Issue by krisbitney** [polywrap/rust-client#197] opened 2023-08-07 20:55 UTC
I am invoking the HelloWorld wrap, which depends on an implementation of the Logging interface. The invocation is succeeding, even though there is no logger plugin to subinvoke. 

When I say "succeeding", I mean that an exception is not thrown and the "logMessage" method of the HelloWorld wrap returns `true`. Nothing is printed to stdout.

HelloWorld wrap: https://github.com/polywrap/demos/tree/main/hello-world/wrapper

**Comment by cbrzn** [comment] 2023-08-08 16:23
hey @krisbitney do u have a reproducible example of this? i can try to get one, do u know where is the hello world wrap deployed?

**Comment by krisbitney** [comment] 2023-08-08 16:28
This example reproduces it: https://github.com/polywrap/kotlin-client/blob/main/examples/HelloWorld.kt

1. clone https://github.com/polywrap/kotlin-client.git and open it in your IDE
2. from the project root, run `./gradlew uniffi && ./gradlew assemble && ./gradlew jvmTest --tests HelloWorld`

**Comment by cbrzn** [comment] 2023-08-08 17:40
i tried to reproduce this in the rust client and when i try to run the example it returns the error:
```
Err(
    InvokeError(
        "wrap://ipfs/Qmd3B3UPXoJYCWMjdnKa7Hs8SXpxLo2tQJfMdqpECbki7J",
        "logMessage",
        "``RuntimeError: __wrap_abort: Error loading wrapper, uri: wrap://ens/wraps.eth:logging@1.0.0: `URI not found: `wrap://ens/wraps.eth:logging@1.0.0``\nFile: src/wrap/module/wrapped.rs\nLocation: [24,21]``",
    ),
)
```
so probably is something regarding how you're handling errors in the kotlin client? or how we're handling invoke errors in ffi? @krisbitney

**Comment by cbrzn** [comment] 2023-08-08 20:05
btw i think we should use this wrap https://github.com/polywrap/logging/blob/main/aggregator/src/index.ts and not the one from the demos repository @krisbitney i have used it in the JS example: https://github.com/polywrap/javascript-client/pull/67/files#diff-9fe73ffdcd829a3ac68b8191c3239457f731279a124aa8d6d5e5c2c5bbc7a829R4

**Comment by krisbitney** [comment] 2023-08-09 12:58
Okay, gotcha, awesome. That works for me.

**Comment by cbrzn** [comment] 2023-08-14 11:33
closing this because this doesn't seem to be a problem from the rust client

**Closed by cbrzn** 2023-08-14 11:33 UTC
Labels: bug
